main: ${PACKAGE}.${NAME}
name: ${NAME}
version: '${VERSION}'
api-version: '1.16'
author: Uxzylon
depend: [ ViaVersion ]
description: Restrict client's Minecraft versions using ViaVersion
permissions:
  ClientVersionRestrictor.bypass:
    description: Bypass the client version restriction
    children:
      ClientVersionRestrictor.*: true